# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_gen_embeddings.ipynb.

# %% auto 0
__all__ = ['client', 'get_embedding']

# %% ../nbs/02_gen_embeddings.ipynb 2
import os
from google import genai
from google.genai import types
import numpy as np

# %% ../nbs/02_gen_embeddings.ipynb 4
client = genai.Client(api_key=os.getenv('GEMINI_API_KEY'))
def get_embedding(contents, model="text-embedding-004"):
    return np.array(client.models.embed_content(model=model, contents=contents, config=types.EmbedContentConfig(task_type="SEMANTIC_SIMILARITY")).embeddings[0].values)
